apiVersion: batch/v1
kind: CronJob
metadata:
  name: hello-job
spec:
  schedule: "*/5 * * * *"
  jobTemplate:
    spec:
      parallelism: 1
      template:
        spec:
          containers:
          - name: hello-job-container
            image: ${{GOOGLE_CLOUD_REGION}}-docker.pkg.dev/${{GOOGLE_CLOUD_PROJECT}}/main-container-registry/cloud-hello-world:latest
            imagePullPolicy: IfNotPresent
            command: ["python", "main.py"]
            env: 
            - name: GOOGLE_CLOUD_PROJECT
              value: ${{GOOGLE_CLOUD_PROJECT}}
            - name: GOOGLE_CLOUD_REGION
              value: ${{GOOGLE_CLOUD_REGION}}
            resources:
              limits:
                memory: "1Gi"
                cpu: "250m"
          restartPolicy: OnFailure